#!/bin/bash

#Logiciels à installer
logiciels=(
  docker
  vscode
  brave
  discord
  vagrant
  exegol
)

#Docker
curl -fsSL "https://get.docker.com/" -o get-docker.sh
sh get-docker.sh

#Exegol
export PATH=/home/sp1der/.local/bin
pipx install exegol
