---
- name: Configurer un poste et installer des paquets
  hosts: all
  become: true
  tasks:
    - name: Mise à jour des packages
      package:
        name: '*'
        state: latest

    - name: Installation des paquets requis
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - wget
        - wireshark
        - keepassxc   
        - build-essential
        - git
        - gpg
        - apt-transport-https
        - pipx

#Logiciels restants : Docker, VS Code, Brave + extensions, Discord, Vagrant, Exegol
